name: fitrat_parent2
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  badges: ^3.1.2
  freezed: ^2.4.3
  shared_preferences: ^2.0.6
  shimmer: ^3.0.0
  permission_handler: ^11.3.1
  cached_network_image: ^3.4.0
  flutter_svg: ^2.0.16
  retrofit: ^4.4.0
  logger: ^2.5.0
  dio: ^5.7.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.0
  intl: ^0.20.2
  intl_utils: ^2.8.8
  equatable: ^2.0.7
  go_router: ^14.7.1
  package_info_plus: ^8.1.3
  mask_text_input_formatter: ^2.9.0
  infinite_scroll_pagination: ^4.1.0
  jwt_decoder: ^2.0.1
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  dropdown_button2: ^2.3.9
  dotted_border: ^2.1.0
  file_picker: ^8.3.1
  multi_dropdown: ^3.0.1
  image_picker: ^1.1.2
  toastification: ^2.3.0
  firebase_core: ^3.11.0
  visibility_detector: ^0.4.0+2
  firebase_messaging: ^15.2.2
  flutter_local_notifications: ^18.0.1
  calendar_date_picker2: ^1.1.8
  get_it: ^8.0.3
  path_provider: ^2.1.5
  open_filex: ^4.6.0
  fluttertoast: ^8.2.1
  readmore: ^3.0.0
  icons_launcher: ^3.0.0
  hive_ce_generator: ^1.8.2
  hive_ce: ^2.10.1
  talker_dio_logger: ^4.6.12
  chucker_flutter: ^1.8.3
  flutter_bloc: ^9.1.0
  carousel_slider: ^5.0.0
  flutter_screenutil: ^5.9.3
  youtube_player_flutter: ^9.1.1
  smooth_page_indicator: ^1.1.0
  connectivity_plus: ^6.1.4
  syncfusion_flutter_pdfviewer: ^29.1.38
  flutter_file_downloader: ^2.1.0
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  riverpod_annotation: ^2.6.1
#  open_file_plus: ^3.4.1+1
  http: ^1.4.0
  sms_autofill: ^2.4.1
  another_flushbar: ^1.12.30


  video_player: ^2.10.0
  #  chuck_interceptor: ^2.2.4
  chuck_interceptor: ^2.1.4
  audioplayers: ^6.4.0
  #  flutter_windowmanager: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  retrofit_generator: '>=8.0.0 <10.0.0' # for Dart 3.3 use ^9.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Outfit
      fonts:
        - asset: fonts/Outfit_Regular.ttf

    - family: outfitMedium
      fonts:
        - asset: fonts/Outfit_Medium.ttf

#        mKH7HOFt
#        aYzhunNM